name: fisiodesporto

services:
  api:
    build: .
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - /opt/fisiodesporto/backend/files/:/opt/hairdresser-backend/files/

