name: fisiodesporto

services:
  api:
    restart: unless-stopped
    build: .
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - /opt/fisiodesporto/hairdresser-backend/files/:/opt/hairdresser-backend/files/
      - /home/vasco/fisio.vraminhos.com/:/opt/hairdresser-backend/ssl/
    network_mode: bridge
